set serveroutput on

--test 1,2
DECLARE
r_emp emp%ROWTYPE;
t_emp emp%ROWTYPE;

PRESIDENT CONSTANT VARCHAR2(9) := 'PRESIDENT';
SALARY_100_DOLLAR CONSTANT NUMBER := 100;
PERCENT_25 CONSTANT NUMBER(5,2) := 0.25;
PERCENT_10 CONSTANT NUMBER(5,2) := 0.1;

BEGIN
SELECT SAL
INTO r_emp.SAL
FROM emp
WHERE JOB=PRESIDENT;

UPDATE emp
SET SAL=SAL-(SAL*PERCENT_25)
WHERE SAL>r_emp.SAL;

END;
/

--test 3,4
DECLARE
r_emp emp%ROWTYPE;
t_emp emp%ROWTYPE;

PRESIDENT CONSTANT VARCHAR2(9) := 'PRESIDENT';
SALARY_100_DOLLAR CONSTANT NUMBER := 100;
PERCENT_25 CONSTANT NUMBER(5,2) := 0.25;
PERCENT_10 CONSTANT NUMBER(5,2) := 0.1;

BEGIN
SELECT SAL
INTO r_emp.SAL
FROM emp
WHERE JOB=PRESIDENT;

UPDATE emp
SET SAL=SAL+(SAL*PERCENT_10)
WHERE SAL<SALARY_100_DOLLAR;

END;
/

--test5,6,7,8
DECLARE
r_emp emp%ROWTYPE;
t_emp emp%ROWTYPE;

PRESIDENT CONSTANT VARCHAR2(9) := 'PRESIDENT';
SALARY_100_DOLLAR CONSTANT NUMBER := 100;
PERCENT_25 CONSTANT NUMBER(5,2) := 0.25;
PERCENT_10 CONSTANT NUMBER(5,2) := 0.1;

BEGIN
SELECT SAL
INTO r_emp.SAL
FROM emp
WHERE JOB=PRESIDENT;

UPDATE emp
SET SAL=SAL-(SAL*PERCENT_25)
WHERE SAL>r_emp.SAL;

UPDATE emp
SET SAL=SAL+(SAL*PERCENT_10)
WHERE SAL<SALARY_100_DOLLAR;

END;
/